-- AlterTable
ALTER TABLE "Camera" ADD COLUMN     "brightness" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "contrast" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "exposure" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "focus" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "iso" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "whiteBalance" TEXT NOT NULL DEFAULT 'auto',
ALTER COLUMN "recordOnMotion" SET DEFAULT false;
